import os
import sys
import json
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from app.core.database import SessionLocal, Base, engine
from app.models import user_team, project, recommendation, task, risk, tool, mentor, delivery
from app.schemas.user_team import UserRegister, TeamCreate, TeamMemberCreate, MemberSkillSchema, MemberSubscriptionSchema
from app.schemas.project import ProjectCreate, TimeBudgetSchema
from app.schemas.recommendation import ArchitectureAcceptRequest
from app.schemas.ps_analyzer import CandidatePSInput, PSEvaluateRequest
from app.services import (
    auth_team_service, project_service, sdlc_engine, arch_engine,
    task_engine, tool_engine, risk_engine, delivery_engine, friendly_service,
    ps_analyzer_engine, mentor_engine
)

def run():
    Base.metadata.drop_all(bind=engine)
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    
    doc = ["# Complete Detailed Output Document: TeamForge AI RAD Prototype\n"]
    doc.append("This document contains the exact detailed outputs generated by every engine in the TeamForge AI lifecycle for a real-world scenario.\n")
    
    # 1. TEAM CREATION
    doc.append("## 1. Team Hub & Onboarding Output")
    lead_in = UserRegister(name="Maya Patel", email="maya@demo.com", password="pwd")
    lead = auth_team_service.register_user(db, lead_in)
    team = auth_team_service.create_team(db, TeamCreate(name="EventForge Squad"), lead.id)
    doc.append(f"**Team Created:** {team.name} (Invite Code: {team.team_code})")
    
    dev1_in = UserRegister(name="Liam Vance", email="liam@demo.com", password="pwd")
    dev1 = auth_team_service.register_user(db, dev1_in)
    
    dev2_in = UserRegister(name="Ethan Cole", email="ethan@demo.com", password="pwd")
    dev2 = auth_team_service.register_user(db, dev2_in)

    dev3_in = UserRegister(name="Chloe Bennett", email="chloe@demo.com", password="pwd")
    dev3 = auth_team_service.register_user(db, dev3_in)

    m_dev1 = user_team.TeamMember(user_id=dev1.id, team_id=team.id, role="developer")
    m_dev2 = user_team.TeamMember(user_id=dev2.id, team_id=team.id, role="developer")
    m_dev3 = user_team.TeamMember(user_id=dev3.id, team_id=team.id, role="ai_assisted")
    db.add_all([m_dev1, m_dev2, m_dev3])
    db.commit()
    db.refresh(m_dev1)
    db.refresh(m_dev2)
    db.refresh(m_dev3)

    m_lead = db.query(user_team.TeamMember).filter(user_team.TeamMember.user_id == lead.id).first()

    db.add_all([
        user_team.MemberSkill(member_id=m_lead.id, name="Python", level="Advanced"),
        user_team.MemberSkill(member_id=m_dev1.id, name="React", level="Advanced"),
        user_team.MemberSkill(member_id=m_dev2.id, name="SQL", level="Advanced"),
        user_team.MemberSkill(member_id=m_dev3.id, name="FastAPI", level="Advanced"),
        user_team.MemberSubscription(member_id=m_dev1.id, tool_name="Figma Pro", tier="Pro"),
        user_team.MemberSubscription(member_id=m_dev3.id, tool_name="Cursor Pro", tier="Pro")
    ])
    db.commit()
    
    # 2. PS EVALUATION
    doc.append("## 2. Problem Statement Ranking Engine Output")
    ps1 = CandidatePSInput(id="ps-1", title="Campus Event Booking Platform", problem_statement="Overselling tickets.", proposed_idea="FastAPI+React event booking.", target_sponsor_track="Stripe")
    ps2 = CandidatePSInput(id="ps-2", title="Zero-Knowledge Medical Ledger", problem_statement="Privacy.", proposed_idea="Custom blockchain.", target_sponsor_track=None)
    eval_req = PSEvaluateRequest(team_id=team.id, time_budget_hours=48, candidate_problem_statements=[ps1, ps2])
    eval_res = ps_analyzer_engine.evaluate_multiple_problem_statements(db, eval_req)
    doc.append("### Winning Problem Statement Breakdown")
    doc.append("`json\n" + json.dumps(eval_res.top_recommended_ps.model_dump(), indent=2) + "\n`\n")
    
    # 3. PROJECT CREATION & FEASIBILITY
    doc.append("## 3. Project Feasibility Engine Output")
    proj_in = ProjectCreate(
        team_id=team.id, name="Campus Event Booking Platform",
        problem_statement="Event organizers struggle with ticket overselling and slow check-ins.", 
        idea="FastAPI + React event booking platform with real-time seat locks and QR ticket passes.",
        time_budget=TimeBudgetSchema(value=48, unit="hours"),
        mandatory_platforms=["Stripe", "Vercel"]
    )
    proj = project_service.create_project(db, proj_in)
    feasibility = project_service.analyze_project_feasibility(db, proj.id)
    doc.append("### Feasibility Assessment (JSON Response)")
    doc.append("`json\n" + json.dumps(feasibility.model_dump(), indent=2) + "\n`\n")

    # Now we can get hub status
    hub_status = auth_team_service.get_team_hub_status(db, proj.id)
    doc.append("### Initial Team Hub Status (JSON Response)")
    doc.append("`json\n" + json.dumps(hub_status.model_dump(), indent=2) + "\n`\n")


    # 4. ARCHITECTURE & SDLC
    doc.append("## 4. Architecture & SDLC Decision Engine Output")
    sdlc = sdlc_engine.recommend_sdlc_model(db, proj.id)
    arch = arch_engine.recommend_architecture(db, proj.id)
    doc.append("### Architecture Recommendation (JSON Response)")
    doc.append("`json\n" + json.dumps({"tier": arch.tier, "components": arch.components}, indent=2) + "\n`\n")
    
    arch_engine.accept_architecture(db, proj.id, arch.id)

    # 5. TASKS
    doc.append("## 5. Task DAG & Bottleneck Engine Output")
    task_res = task_engine.decompose_tasks(db, proj.id)
    doc.append("### Task Decomposition Graph Summary")
    doc.append(f"**Total Tasks Generated:** {len(task_res.tasks)}")
    doc.append(f"**Critical Path Bottlenecks:** {len(task_res.bottlenecks)}")
    
    # Make some tasks depend on others to show actionable blockers
    tasks_objs = db.query(task.Task).filter(task.Task.project_id == proj.id).all()
    if len(tasks_objs) >= 2:
        tasks_objs[1].depends_on = [tasks_objs[0].id]
        tasks_objs[0].assignment = task.TaskAssignment(member_id=m_dev2.id, reasoning="best fit")
        tasks_objs[1].assignment = task.TaskAssignment(member_id=m_dev1.id, reasoning="best fit")
        db.commit()

    hub_status2 = auth_team_service.get_team_hub_status(db, proj.id)
    doc.append("### Team Hub Actionable Blocker Status (JSON)")
    doc.append("`json\n" + json.dumps(hub_status2.model_dump(), indent=2) + "\n`\n")

    doc.append("### Sample Task Record (JSON)")
    if tasks_objs:
        t_dict = {
            "title": tasks_objs[0].title, "status": tasks_objs[0].status,
            "dependencies": tasks_objs[0].depends_on, "assignee_id": tasks_objs[0].assignment.member_id if tasks_objs[0].assignment else None
        }
        doc.append("`json\n" + json.dumps(t_dict, indent=2) + "\n`\n")

    # 6. FRIENDLY GAME PLAN
    doc.append("## 6. Friendly Transformation Layer (ELI5 Guides) Output")
    friendly = friendly_service.generate_friendly_game_plan(db, proj.id)
    doc.append("### Generated Teammate Work Cards")
    for card in friendly.team_cards:
        doc.append(f"#### {card.friendly_role_title}")
        doc.append(f"**What you are building:** {card.what_you_are_building}")
        if card.primary_tool_guide:
            doc.append("**Tool Guide:** " + card.primary_tool_guide.tool_name)
            doc.append("**Why:** " + getattr(card.primary_tool_guide, 'why_this_tool', ''))
            doc.append("**Step-by-Step Instructions (ELI5):**")
            for step in getattr(card.primary_tool_guide, 'step_by_step_instructions', []):
                doc.append(f"- {step}")
            doc.append(f"\n**Starter Prompt:** {getattr(card.primary_tool_guide, 'quick_starter_prompt', '')}\n")

    # 7. PROJECT BRAIN (MENTOR)
    doc.append("## 7. Omniscient AI Project Brain Output")
    q1 = mentor_engine.ask_mentor(db, proj.id, m_dev1.id, "How do I connect my React frontend button to the backend API?")
    doc.append("### Question 1: Cross-Teammate API Connection")
    doc.append(f"**Answer:**\n{q1.answer}\n")
    doc.append(f"**Sources Referenced:** {q1.sources}\n")

    q2 = mentor_engine.ask_mentor(db, proj.id, m_dev2.id, "How do we prevent double-booking seats when two users click at once?")
    doc.append("### Question 2: Database Concurrency Locking")
    doc.append(f"**Answer:**\n{q2.answer}\n")
    doc.append(f"**Sources Referenced:** {q2.sources}\n")

    q3 = mentor_engine.ask_mentor(db, proj.id, m_lead.id, "Why did you choose a Modular Monolith architecture instead of Microservices?")
    doc.append("### Question 3: Architecture Rationale (Explainability)")
    doc.append(f"**Answer:**\n{q3.answer}\n")
    
    # 8. DELIVERY
    doc.append("## 8. Delivery & Artifacts Output")
    readme = delivery_engine.generate_architecture_readme(db, proj.id)
    doc.append("### Generated Architecture README")
    doc.append("`markdown\n" + readme.content + "\n`\n")

    pitch = delivery_engine.generate_pitch_deck_outline(db, proj.id)
    doc.append("### Generated Pitch Deck")
    doc.append("`markdown\n" + pitch.content + "\n`\n")

    with open('C:/Users/dhruv/.gemini/antigravity/brain/0d67913c-7f70-4972-8aac-ad238bf4bd01/complete_system_outputs.md', 'w', encoding='utf-8') as f:
        f.write('\n'.join(doc))

run()
