import uuid
from typing import Dict, Any, List, Optional
from sqlalchemy.orm import Session
from ..models.delivery import GitHubLink, GeneratedArtifact
from ..models.project import Project
from ..models.task import Task
from ..models.recommendation import SDLCRecommendation, ArchitectureRecommendation, DataArchitectureRecommendation
from ..models.risk import Risk
from ..core.security import HTTPException

def link_github_repo(db: Session, project_id: str, repo_url: Optional[str] = None) -> GitHubLink:
    project = db.query(Project).filter(Project.id == project_id).first()
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
        
    if not repo_url:
        clean_title = "".join(c if c.isalnum() else "-" for c in project.title.lower()).strip("-")
        repo_url = f"https://github.com/teamforge-demo/{clean_title}"
        
    link = db.query(GitHubLink).filter(GitHubLink.project_id == project_id).first()
    if not link:
        link = GitHubLink(
            id=str(uuid.uuid4()),
            project_id=project_id,
            repo_url=repo_url,
            status="connected",
            synced_issues_json="[]"
        )
        db.add(link)
    else:
        link.repo_url = repo_url
        link.status = "connected"
        
    db.commit()
    db.refresh(link)
    return link

def sync_tasks_to_github(db: Session, project_id: str) -> Dict[str, Any]:
    project = db.query(Project).filter(Project.id == project_id).first()
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
        
    link = db.query(GitHubLink).filter(GitHubLink.project_id == project_id).first()
    if not link:
        # Auto-create link if missing
        link = link_github_repo(db, project_id)
        
    tasks = db.query(Task).filter(Task.project_id == project_id).order_by(Task.created_at.asc()).all()
    
    synced_items = []
    for idx, task in enumerate(tasks, start=1):
        item = {
            "task_id": task.id,
            "issue_number": idx,
            "title": f"[{task.component_name}] {task.title}",
            "issue_url": f"{link.repo_url}/issues/{idx}"
        }
        synced_items.append(item)
        
    link.synced_issues = synced_items
    db.commit()
    db.refresh(link)
    
    return {
        "project_id": project_id,
        "repo_url": link.repo_url,
        "synced_issues": synced_items
    }

def get_github_status(db: Session, project_id: str) -> Dict[str, Any]:
    link = db.query(GitHubLink).filter(GitHubLink.project_id == project_id).first()
    if not link:
        return {
            "connected": False,
            "repo_url": None,
            "synced_count": 0,
            "synced_issues": []
        }
    return {
        "connected": True,
        "repo_url": link.repo_url,
        "synced_count": len(link.synced_issues),
        "synced_issues": link.synced_issues
    }

def generate_architecture_readme(db: Session, project_id: str) -> GeneratedArtifact:
    project = db.query(Project).filter(Project.id == project_id).first()
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
        
    sdlc = db.query(SDLCRecommendation).filter(
        SDLCRecommendation.project_id == project_id
    ).order_by(SDLCRecommendation.created_at.desc()).first()
    
    arch = db.query(ArchitectureRecommendation).filter(
        ArchitectureRecommendation.project_id == project_id
    ).order_by(ArchitectureRecommendation.created_at.desc()).first()
    
    data_arch = db.query(DataArchitectureRecommendation).filter(
        DataArchitectureRecommendation.project_id == project_id
    ).order_by(DataArchitectureRecommendation.created_at.desc()).first()
    
    tasks = db.query(Task).filter(Task.project_id == project_id).all()
    
    sdlc_model = sdlc.recommended_model if sdlc else "Agile Kanban (Adaptive)"
    sdlc_rationale = sdlc.reasoning if sdlc else "Tailored for time-constrained rapid delivery."
    arch_tier = arch.tier if arch else "single"
    arch_rationale = arch.reasoning if arch else "Modular Monolith design for fast development velocity."
    components = arch.components if arch else [
        {"name": "API Gateway & Auth", "responsibility": "Identity & token verification"},
        {"name": "Core Engine", "responsibility": "Domain business logic & algorithms"},
        {"name": "Data Storage", "responsibility": "Relational entities & state management"}
    ]
    
    comp_section = "\n".join([f"- **{c.get('name', 'Module')}**: {c.get('responsibility', 'Core service component')}" for c in components])
    
    readme_content = f"""# {project.title}

> **Autonomous System Architecture & Engineering Plan**
> Generated by TeamForge AI

---

## 1. Executive Summary & Problem Scope
**Problem Statement:**
{project.problem_statement}

**Time Budget:** {project.time_budget_value} {project.time_budget_unit}  
**Feasibility Verdict:** {project.feasibility_verdict or "FEASIBLE"}  
**Analysis:** {project.feasibility_reasoning or "High confidence execution feasible within allocated sprint capacity."}

---

## 2. SDLC Methodology
- **Recommended Model:** `{sdlc_model.upper()}`
- **Architectural Rationale:** {sdlc_rationale}

---

## 3. Architecture Blueprint ({arch_tier.upper()})
- **Design Pattern:** Modular Monolith (Separation of Concerns with unified deployment)
- **Rationale:** {arch_rationale}

### Core Component Breakdown:
{comp_section}

---

## 4. Data Architecture & Storage Choices
- **Ownership Model:** Component-isolated schemas with strict single-writer policy.
- **Storage Decisions:**
  - Relational Database (PostgreSQL / SQLite for development): ACID guarantees for projects, tasks, user skills, and team structures.
  - JSON Schema attributes: Flexible attribute trees for dynamic recommendation outputs and explainability graphs.

---

## 5. Workstream Breakdown & Task DAG ({len(tasks)} Total Work Items)
"""
    if tasks:
        for t in tasks:
            deps = ", ".join(t.depends_on) if t.depends_on else "None"
            readme_content += f"- **[{t.component_name}] {t.title}** (Estimated: {t.estimated_hours}h | Depends on: {deps})\n"
    else:
        readme_content += "- *No decomposed tasks generated yet.*\n"

    readme_content += """
---

## 6. Development & Run Instructions
```bash
# Clone the repository
git clone <repo-url>
cd <repo-name>

# Install backend dependencies
pip install -r requirements.txt

# Run database migrations and seed
python backend/seed_data.py

# Launch the FastAPI dev server
uvicorn app.main:app --reload --port 8000
```
"""

    artifact = GeneratedArtifact(
        id=str(uuid.uuid4()),
        project_id=project_id,
        artifact_type="architecture_readme",
        title=f"Architecture README - {project.title}",
        content=readme_content
    )
    db.add(artifact)
    db.commit()
    db.refresh(artifact)
    return artifact

def generate_pitch_deck_outline(db: Session, project_id: str) -> GeneratedArtifact:
    project = db.query(Project).filter(Project.id == project_id).first()
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
        
    risks = db.query(Risk).filter(Risk.project_id == project_id).all()
    tasks = db.query(Task).filter(Task.project_id == project_id).all()
    
    pitch_content = f"""# Pitch Deck & Demo Script: {project.title}

### Slide 1: The Vision & Team
- **Headline:** {project.title} — Autonomous Engineering Copilot
- **Tagline:** Empowering engineering teams to architect, decompose, and ship production software in record time.
- **Presenter:** Team Lead & Engineering Core

---

### Slide 2: The Problem & Developer Pain
- **Core Friction:** Teams lose 40% of time in early hackathons and sprints deliberating SDLC choices, micro-architecture debates, and manual task assignment.
- **Problem Statement:** "{project.problem_statement}"
- **Impact:** Misaligned skills, architecture debt, and missed sprint deadlines.

---

### Slide 3: The Solution — TeamForge AI
- **What We Built:** An end-to-end intelligent engineering orchestration engine.
- **Key Capabilities:**
  - Automated problem analysis & capability extraction.
  - Multi-tier SDLC and modular architecture decision trees with transparent explainability.
  - Dependency-aware Task Decomposition DAG with automated bottleneck identification.
  - Skill & Subscription-aware task assignment.

---

### Slide 4: Technical Architecture & Execution
- **System Architecture:** Clean Domain-Driven Modular Monolith with zero-ops local deployment capability.
- **Total Work Items:** {len(tasks)} prioritized DAG nodes.
- **Capacity Fit:** Feasibility confirmed within {project.time_budget_value} {project.time_budget_unit} sprint target.

---

### Slide 5: Risk Mitigation & Resiliency
"""
    if risks:
        for r in risks[:3]:
            pitch_content += f"- **Risk ({r.severity}):** {r.title} ➔ *Mitigation:* {r.mitigation}\n"
    else:
        pitch_content += "- Automated real-time risk scoring and mitigation triggers deployed.\n"

    pitch_content += f"""
---

### Slide 6: Live Demonstration Script
1. **Input Problem Statement:** Submit prompt and watch real-time capability extraction.
2. **Review Architecture Rationale:** Inspect why Modular Monolith was chosen and why Microservices was rejected.
3. **Inspect Task DAG & Bottlenecks:** Visualize critical path and optimal resource assignment.
4. **Export Artifacts:** 1-click GitHub Issue synchronization and Architecture README generation.

---

### Slide 7: Roadmap & Next Steps
- **Phase 1:** Core RAD prototype backend with 12 engineering lifecycle engines (Completed).
- **Phase 2:** Cloud PostgreSQL migration and real-time WebSocket mentor streaming.
- **Phase 3:** IDE extension (VS Code / JetBrains) integration for live sprint tracking.
"""

    artifact = GeneratedArtifact(
        id=str(uuid.uuid4()),
        project_id=project_id,
        artifact_type="pitch_deck",
        title=f"Pitch Deck Outline - {project.title}",
        content=pitch_content
    )
    db.add(artifact)
    db.commit()
    db.refresh(artifact)
    return artifact
